export enum LiveEventType {
    START_LIVE = 'START_LIVE',
    REFRESH_LIVE = 'REFRESH_LIVE',
    PIN_PRODUCT = 'PIN_PRODUCT',
    EDIT_PRODUCT = 'EDIT_PRODUCT',
    STOP_LIVE = 'STOP_LIVE',
    UPDATE_VIEWCOUNT = 'UPDATE_VIEWCOUNT',
    PIN_PROMOTION = 'PIN_PROMOTION'
}  
